# Generated by Django 3.0.2 on 2020-01-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='FullName',
            new_name='Name',
        ),
    ]
